Add cmdline feature
rust-vmm/linux-loader pull request #109
Opened 2022-04-20 07:46 UTC by uran0sH

### Summary of the PR

You can use cmdline loader only.

Signed-off-by: uran0sH <huangwenyuu@outlook.com>

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] Any newly added `unsafe` code is properly documented.

2022-04-20 10:50 UTC, andreeaflorescu requested changes
We should also add a test to check that the PR actually fixes the bug. To do that, we should create a similar test to this one: https://github.com/rust-vmm/linux-loader/blob/3d80c65a62ef032a835332ddd64dddd913f641ec/.buildkite/custom-tests.json#L11. In the test we should run ```cargo build --no-default-features```.

2022-04-20 10:50 UTC, andreeaflorescu commented on Cargo.toml
> +cmdline = []
We should make it possible to build without any features. Adding `cmdline` as a feature is not necessary, and increases the complexity.

2022-04-21 07:09 UTC, andreeaflorescu approved these changes

2022-04-21 07:45 UTC, lauralt approved these changes

2022-04-21 07:45 UTC, merged