Introduce riscv architecture
rust-vmm/linux-loader pull request #190
Opened 2024-09-11 09:22 UTC by TimePrinciple

### Summary of the PR

Introduce RISC-V architecture to `loader`, bringing #163 forward.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

2024-10-15 07:33 UTC, TimePrinciple commented
@roypat @rbradford @ShadowCurse  PTAL when convenient :)

2024-10-16 10:12 UTC, rbradford submitted a review, later dismissed

2024-10-16 10:25 UTC, roypat requested changes
I feel like there is a lot of code duplicated between the ARM and RISC implementations that doesn't really need to be duplicated like this. Can you have a look at that, to see where we can reuse instead? :o

2024-10-16 10:25 UTC, roypat commented on benches/riscv64/mod.rs
Instead of duplicating this entire benchmark, let's just rename the `aarch64.rs` file to something more appropriate (`fdt.rs`, maybe), and simply have it cfg'd with `any(target_arch = "aarch64", target_arch = "riscv64")

2024-10-16 10:25 UTC, roypat commented on src/configurator/riscv64/fdt.rs
This file is also a 1:1 copy of the one in the aarch64 module. Let's figure out a way to reuse these somehow

2024-10-16 10:25 UTC, roypat commented on src/loader/riscv64/pe/mod.rs
> +    fn load<F, M: GuestMemory>(
This is also very similar to the existing aarch64 code. Can we reuse part of it somehow?

2024-10-16 10:27 UTC, TimePrinciple commented
> I feel like there is a lot of code duplicated between the ARM and RISC implementations that doesn't really need to be duplicated like this. Can you have a look at that, to see where we can reuse instead? :o

Yes, I noticed that, I just copied these files incase there is something to be diverged in the future

I can try to merge the common part as possible, but what should we name that, like `risc`s ? :o

2024-10-16 11:16 UTC, rbradford commented
> > I feel like there is a lot of code duplicated between the ARM and RISC implementations that doesn't really need to be duplicated like this. Can you have a look at that, to see where we can reuse instead? :o
> 
> Yes, I noticed that, I just copied these files incase there is something to be diverged in the future
> 
> I can try to merge the common part as possible, but what should we name that, like `risc`s ? :o

Maybe move he fdt code can be moved to a higher level and then `pub use` to expose it from the arch module and keep the same API?

2024-10-22 07:14 UTC, rbradford approved these changes
After the refactoring this change is lovely and compact.

2024-10-22 08:30 UTC, roypat approved these changes

2024-10-22 13:09 UTC, merged